### ISSUE TITLE
Offline maps, please help!

### ISSUE THREAD

**Issue by hbzhang** [ActionStreetMap/demo#18]
There, I look through the source code. I found that the project loads offline map from demo/Assets/Resources/

There are many files.  How I can get another specific place work with demo code? What I mean is that I want to use a place in U.S. for example. How I can replace the default files with my files. Also how I can generate these files for my location?

Thanks!!

**Comment by reinterpretcat** [comment]
This class is key to start exploring how it works:
https://github.com/ActionStreetMap/framework/blob/2c7d14d9925d8d1363146304d980e8b905a1ee85/ActionStreetMap.Maps/Data/ElementSourceProvider.cs

Take a look at defaults here:
https://github.com/ActionStreetMap/framework/blob/2c7d14d9925d8d1363146304d980e8b905a1ee85/ActionStreetMap.Explorer/Infrastructure/ConfigBuilder.cs

..and then how paths are processed:
https://github.com/ActionStreetMap/demo/blob/6640ad7e9166a32d49d4a618a587c2915df1c319/Assets/Scripts/Demo/PathResolver.cs

BTW, I would recommend to switch to utymap project (however, I'm not working on it actively as well)

**Comment by hbzhang** [comment]
Thank you!! I will look into it. I have also looked into utymap. It is a good project! Thanks for your effort. I think it has a very nice potential!
