### ISSUE TITLE
Missing asset db

### ISSUE THREAD

**Issue by middleJack** [ActionStreetMap/demo#6]
I'm sorry to open an issue rather than offering a solution:
I you export this project for the first time, Unity drops:
"Rebuilding Library because the asset database could not be found!"
Removing Assets/UnityVS/Editor/SyntaxTree.VisualStudio.Unity.Bridge.dll because the asset does not exist
Removing Assets/UnityVS/Editor/SyntaxTree.VisualStudio.Unity.Messaging.dll because the asset does not exist
Removing Assets/UnityVS/Editor/UnityVS.VersionSpecific.dll because the asset does not exist

**Comment by reinterpretcat** [comment]
Thanks for reporting that!

Probably you have to install this plugin: http://unityvs.com

Btw, I'm going to update entire demo project soon with new version of framework which has been completely changed (you can read more here http://actionstreetmap.github.io/demo/). 

So, will close this issue once it is done

**Comment by middleJack** [comment]
Thanks! I'm unwilling to test it!
