### ISSUE TITLE
Unreal Engine 4 Support for ActionStreetMap

### ISSUE THREAD

**Issue by HeadClot** [ActionStreetMap/demo#9]
Hey,
I am not sure really where to put this.
Just thought I would ask are there any plans for supporting Unreal Engine 4?

If you have any doubts about the port over to unreal engine 4 please let me know.

Also I might be able to help with 3D Art assets.
- Benjamin

**Comment by reinterpretcat** [comment]
Most of the code are not depending on unity at all (even no references of UnityEngine.dll). However, there is dependency on CLR runtime as framework is written using pure C# (compiled by Microsoft compiler, .NET 3.5 is selected as target platform).
As far as I know, Unreal Engine doesn't support C#/CLR. So, porting will require at least line by line conversion to different language, probably unmanaged. That will require strong understanding differences between platforms to avoid any performance degradation.

**Comment by HeadClot** [comment]
Hey @ibuiluk -

Thank you for the prompt reply.You might be able to try this - https://github.com/enlight/klawr

It uses C#/CLR runtimes but it is experimental.

Either way do you need an artist?

**Comment by reinterpretcat** [comment]
So far, I'm one who is working on the project (in my spare time!) and switching to porting will reduce my capacity on adding new things/fixing existing issues. Finally, it may be just waste of time as this plugin is experimental.

This demo is not a real game, it's just presentation of framework and its features. The general idea is to develop "platform" for creating map-based games (and not only games!). Of course, in future I may consider to create some real game/application (maybe for VR devices) to have some commercial profit. 
At that time, I will probably need to gather team and invite an artist (after developing game concept).
